/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProjectId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileMetadataInput = IDL.Record({
  'fileType' : IDL.Text,
  'filename' : IDL.Text,
  'projectId' : ProjectId,
  'fileKey' : ExternalBlob,
});
export const FileId = IDL.Nat;
export const Timestamp = IDL.Int;
export const FileMetadata = IDL.Record({
  'id' : FileId,
  'fileType' : IDL.Text,
  'filename' : IDL.Text,
  'projectId' : ProjectId,
  'uploadedAt' : Timestamp,
  'fileKey' : ExternalBlob,
});
export const ProjectInput = IDL.Record({
  'insights' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'githubUrl' : IDL.Opt(IDL.Text),
  'results' : IDL.Text,
  'liveDemoUrl' : IDL.Opt(IDL.Text),
  'datasetDescription' : IDL.Text,
  'approach' : IDL.Text,
  'problemStatement' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : ProjectId,
  'insights' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'githubUrl' : IDL.Opt(IDL.Text),
  'results' : IDL.Text,
  'liveDemoUrl' : IDL.Opt(IDL.Text),
  'datasetDescription' : IDL.Text,
  'viewCount' : IDL.Nat,
  'approach' : IDL.Text,
  'problemStatement' : IDL.Text,
});
export const TestimonialInput = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'company' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'approved' : IDL.Bool,
});
export const TestimonialId = IDL.Nat;
export const Testimonial = IDL.Record({
  'id' : TestimonialId,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'company' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'approved' : IDL.Bool,
});
export const ContactId = IDL.Nat;
export const Analytics = IDL.Record({
  'totalViews' : IDL.Nat,
  'contactCount' : IDL.Nat,
  'projectCount' : IDL.Nat,
  'featuredCount' : IDL.Nat,
});
export const ContactSubmission = IDL.Record({
  'id' : ContactId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const ContactInput = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addFileMetadata' : IDL.Func([FileMetadataInput], [FileMetadata], []),
  'createProject' : IDL.Func([ProjectInput], [Project], []),
  'createTestimonial' : IDL.Func([TestimonialInput], [Testimonial], []),
  'deleteContact' : IDL.Func([ContactId], [IDL.Bool], []),
  'deleteFileMetadata' : IDL.Func([FileId], [IDL.Bool], []),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'deleteTestimonial' : IDL.Func([TestimonialId], [IDL.Bool], []),
  'getAdmin' : IDL.Func([], [IDL.Principal], ['query']),
  'getAnalytics' : IDL.Func([], [Analytics], []),
  'getFilesByProject' : IDL.Func(
      [ProjectId],
      [IDL.Vec(FileMetadata)],
      ['query'],
    ),
  'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], []),
  'incrementViewCount' : IDL.Func([ProjectId], [], []),
  'init' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
  'listFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'markContactRead' : IDL.Func([ContactId], [IDL.Bool], []),
  'setAdmin' : IDL.Func([IDL.Principal], [], []),
  'submitContact' : IDL.Func([ContactInput], [ContactSubmission], []),
  'toggleFeatured' : IDL.Func([ProjectId], [IDL.Bool], []),
  'updateProject' : IDL.Func([ProjectId, ProjectInput], [IDL.Bool], []),
  'updateTestimonial' : IDL.Func(
      [TestimonialId, TestimonialInput],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProjectId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileMetadataInput = IDL.Record({
    'fileType' : IDL.Text,
    'filename' : IDL.Text,
    'projectId' : ProjectId,
    'fileKey' : ExternalBlob,
  });
  const FileId = IDL.Nat;
  const Timestamp = IDL.Int;
  const FileMetadata = IDL.Record({
    'id' : FileId,
    'fileType' : IDL.Text,
    'filename' : IDL.Text,
    'projectId' : ProjectId,
    'uploadedAt' : Timestamp,
    'fileKey' : ExternalBlob,
  });
  const ProjectInput = IDL.Record({
    'insights' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'githubUrl' : IDL.Opt(IDL.Text),
    'results' : IDL.Text,
    'liveDemoUrl' : IDL.Opt(IDL.Text),
    'datasetDescription' : IDL.Text,
    'approach' : IDL.Text,
    'problemStatement' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : ProjectId,
    'insights' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'githubUrl' : IDL.Opt(IDL.Text),
    'results' : IDL.Text,
    'liveDemoUrl' : IDL.Opt(IDL.Text),
    'datasetDescription' : IDL.Text,
    'viewCount' : IDL.Nat,
    'approach' : IDL.Text,
    'problemStatement' : IDL.Text,
  });
  const TestimonialInput = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'company' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'approved' : IDL.Bool,
  });
  const TestimonialId = IDL.Nat;
  const Testimonial = IDL.Record({
    'id' : TestimonialId,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'company' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'approved' : IDL.Bool,
  });
  const ContactId = IDL.Nat;
  const Analytics = IDL.Record({
    'totalViews' : IDL.Nat,
    'contactCount' : IDL.Nat,
    'projectCount' : IDL.Nat,
    'featuredCount' : IDL.Nat,
  });
  const ContactSubmission = IDL.Record({
    'id' : ContactId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const ContactInput = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addFileMetadata' : IDL.Func([FileMetadataInput], [FileMetadata], []),
    'createProject' : IDL.Func([ProjectInput], [Project], []),
    'createTestimonial' : IDL.Func([TestimonialInput], [Testimonial], []),
    'deleteContact' : IDL.Func([ContactId], [IDL.Bool], []),
    'deleteFileMetadata' : IDL.Func([FileId], [IDL.Bool], []),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'deleteTestimonial' : IDL.Func([TestimonialId], [IDL.Bool], []),
    'getAdmin' : IDL.Func([], [IDL.Principal], ['query']),
    'getAnalytics' : IDL.Func([], [Analytics], []),
    'getFilesByProject' : IDL.Func(
        [ProjectId],
        [IDL.Vec(FileMetadata)],
        ['query'],
      ),
    'getProject' : IDL.Func([ProjectId], [IDL.Opt(Project)], []),
    'incrementViewCount' : IDL.Func([ProjectId], [], []),
    'init' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], []),
    'listFeaturedProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'markContactRead' : IDL.Func([ContactId], [IDL.Bool], []),
    'setAdmin' : IDL.Func([IDL.Principal], [], []),
    'submitContact' : IDL.Func([ContactInput], [ContactSubmission], []),
    'toggleFeatured' : IDL.Func([ProjectId], [IDL.Bool], []),
    'updateProject' : IDL.Func([ProjectId, ProjectInput], [IDL.Bool], []),
    'updateTestimonial' : IDL.Func(
        [TestimonialId, TestimonialInput],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };