/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analytics {
  'totalViews' : bigint,
  'contactCount' : bigint,
  'projectCount' : bigint,
  'featuredCount' : bigint,
}
export type ContactId = bigint;
export interface ContactInput {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContactSubmission {
  'id' : ContactId,
  'subject' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'read' : boolean,
  'email' : string,
  'message' : string,
}
export type ExternalBlob = Uint8Array;
export type FileId = bigint;
export interface FileMetadata {
  'id' : FileId,
  'fileType' : string,
  'filename' : string,
  'projectId' : ProjectId,
  'uploadedAt' : Timestamp,
  'fileKey' : ExternalBlob,
}
export interface FileMetadataInput {
  'fileType' : string,
  'filename' : string,
  'projectId' : ProjectId,
  'fileKey' : ExternalBlob,
}
export interface Project {
  'id' : ProjectId,
  'insights' : string,
  'title' : string,
  'featured' : boolean,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'description' : string,
  'githubUrl' : [] | [string],
  'results' : string,
  'liveDemoUrl' : [] | [string],
  'datasetDescription' : string,
  'viewCount' : bigint,
  'approach' : string,
  'problemStatement' : string,
}
export type ProjectId = bigint;
export interface ProjectInput {
  'insights' : string,
  'title' : string,
  'featured' : boolean,
  'tags' : Array<string>,
  'description' : string,
  'githubUrl' : [] | [string],
  'results' : string,
  'liveDemoUrl' : [] | [string],
  'datasetDescription' : string,
  'approach' : string,
  'problemStatement' : string,
}
export interface Testimonial {
  'id' : TestimonialId,
  'name' : string,
  'role' : string,
  'quote' : string,
  'company' : string,
  'imageUrl' : [] | [string],
  'approved' : boolean,
}
export type TestimonialId = bigint;
export interface TestimonialInput {
  'name' : string,
  'role' : string,
  'quote' : string,
  'company' : string,
  'imageUrl' : [] | [string],
  'approved' : boolean,
}
export type Timestamp = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFileMetadata' : ActorMethod<[FileMetadataInput], FileMetadata>,
  'createProject' : ActorMethod<[ProjectInput], Project>,
  'createTestimonial' : ActorMethod<[TestimonialInput], Testimonial>,
  'deleteContact' : ActorMethod<[ContactId], boolean>,
  'deleteFileMetadata' : ActorMethod<[FileId], boolean>,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'deleteTestimonial' : ActorMethod<[TestimonialId], boolean>,
  'getAdmin' : ActorMethod<[], Principal>,
  'getAnalytics' : ActorMethod<[], Analytics>,
  'getFilesByProject' : ActorMethod<[ProjectId], Array<FileMetadata>>,
  'getProject' : ActorMethod<[ProjectId], [] | [Project]>,
  'incrementViewCount' : ActorMethod<[ProjectId], undefined>,
  'init' : ActorMethod<[], undefined>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'listContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'listFeaturedProjects' : ActorMethod<[], Array<Project>>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'listTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'markContactRead' : ActorMethod<[ContactId], boolean>,
  'setAdmin' : ActorMethod<[Principal], undefined>,
  'submitContact' : ActorMethod<[ContactInput], ContactSubmission>,
  'toggleFeatured' : ActorMethod<[ProjectId], boolean>,
  'updateProject' : ActorMethod<[ProjectId, ProjectInput], boolean>,
  'updateTestimonial' : ActorMethod<[TestimonialId, TestimonialInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];