/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ContactInput {
    subject: string;
    name: string;
    email: string;
    message: string;
}
export type Timestamp = bigint;
export interface FileMetadata {
    id: FileId;
    fileType: string;
    filename: string;
    projectId: ProjectId;
    uploadedAt: Timestamp;
    fileKey: ExternalBlob;
}
export interface ContactSubmission {
    id: ContactId;
    subject: string;
    name: string;
    createdAt: Timestamp;
    read: boolean;
    email: string;
    message: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TestimonialInput {
    name: string;
    role: string;
    quote: string;
    company: string;
    imageUrl?: string;
    approved: boolean;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ProjectInput {
    insights: string;
    title: string;
    featured: boolean;
    tags: Array<string>;
    description: string;
    githubUrl?: string;
    results: string;
    liveDemoUrl?: string;
    datasetDescription: string;
    approach: string;
    problemStatement: string;
}
export interface FileMetadataInput {
    fileType: string;
    filename: string;
    projectId: ProjectId;
    fileKey: ExternalBlob;
}
export interface Analytics {
    totalViews: bigint;
    contactCount: bigint;
    projectCount: bigint;
    featuredCount: bigint;
}
export type ProjectId = bigint;
export type FileId = bigint;
export type ContactId = bigint;
export interface Project {
    id: ProjectId;
    insights: string;
    title: string;
    featured: boolean;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    githubUrl?: string;
    results: string;
    liveDemoUrl?: string;
    datasetDescription: string;
    viewCount: bigint;
    approach: string;
    problemStatement: string;
}
export type TestimonialId = bigint;
export interface Testimonial {
    id: TestimonialId;
    name: string;
    role: string;
    quote: string;
    company: string;
    imageUrl?: string;
    approved: boolean;
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    addFileMetadata(input: FileMetadataInput): Promise<FileMetadata>;
    createProject(input: ProjectInput): Promise<Project>;
    createTestimonial(input: TestimonialInput): Promise<Testimonial>;
    deleteContact(id: ContactId): Promise<boolean>;
    deleteFileMetadata(id: FileId): Promise<boolean>;
    deleteProject(id: ProjectId): Promise<boolean>;
    deleteTestimonial(id: TestimonialId): Promise<boolean>;
    getAdmin(): Promise<Principal>;
    getAnalytics(): Promise<Analytics>;
    getFilesByProject(projectId: ProjectId): Promise<Array<FileMetadata>>;
    getProject(id: ProjectId): Promise<Project | null>;
    incrementViewCount(id: ProjectId): Promise<void>;
    init(): Promise<void>;
    isAdmin(p: Principal): Promise<boolean>;
    listContacts(): Promise<Array<ContactSubmission>>;
    listFeaturedProjects(): Promise<Array<Project>>;
    listProjects(): Promise<Array<Project>>;
    listTestimonials(): Promise<Array<Testimonial>>;
    markContactRead(id: ContactId): Promise<boolean>;
    setAdmin(newAdmin: Principal): Promise<void>;
    submitContact(input: ContactInput): Promise<ContactSubmission>;
    toggleFeatured(id: ProjectId): Promise<boolean>;
    updateProject(id: ProjectId, input: ProjectInput): Promise<boolean>;
    updateTestimonial(id: TestimonialId, input: TestimonialInput): Promise<boolean>;
}
import type { ExternalBlob as _ExternalBlob, FileId as _FileId, FileMetadata as _FileMetadata, FileMetadataInput as _FileMetadataInput, Project as _Project, ProjectId as _ProjectId, ProjectInput as _ProjectInput, Testimonial as _Testimonial, TestimonialId as _TestimonialId, TestimonialInput as _TestimonialInput, Timestamp as _Timestamp, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addFileMetadata(arg0: FileMetadataInput): Promise<FileMetadata> {
        if (this.processError) {
            try {
                const result = await this.actor.addFileMetadata(await to_candid_FileMetadataInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_FileMetadata_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFileMetadata(await to_candid_FileMetadataInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_FileMetadata_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProject(arg0: ProjectInput): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(to_candid_ProjectInput_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Project_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(to_candid_ProjectInput_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Project_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTestimonial(arg0: TestimonialInput): Promise<Testimonial> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestimonial(to_candid_TestimonialInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Testimonial_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestimonial(to_candid_TestimonialInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Testimonial_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteContact(arg0: ContactId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteFileMetadata(arg0: FileId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFileMetadata(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFileMetadata(arg0);
            return result;
        }
    }
    async deleteProject(arg0: ProjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteTestimonial(arg0: TestimonialId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTestimonial(arg0);
            return result;
        }
    }
    async getAdmin(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmin();
            return result;
        }
    }
    async getAnalytics(): Promise<Analytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getFilesByProject(arg0: ProjectId): Promise<Array<FileMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilesByProject(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilesByProject(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProject(arg0: ProjectId): Promise<Project | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProject(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProject(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementViewCount(arg0: ProjectId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementViewCount(arg0);
            return result;
        }
    }
    async init(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.init();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.init();
            return result;
        }
    }
    async isAdmin(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin(arg0);
            return result;
        }
    }
    async listContacts(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContacts();
            return result;
        }
    }
    async listFeaturedProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFeaturedProjects();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFeaturedProjects();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProjects();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProjects();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTestimonials();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTestimonials();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async markContactRead(arg0: ContactId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markContactRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContactRead(arg0);
            return result;
        }
    }
    async setAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin(arg0);
            return result;
        }
    }
    async submitContact(arg0: ContactInput): Promise<ContactSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return result;
        }
    }
    async toggleFeatured(arg0: ProjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFeatured(arg0);
            return result;
        }
    }
    async updateProject(arg0: ProjectId, arg1: ProjectInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_ProjectInput_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_ProjectInput_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTestimonial(arg0: TestimonialId, arg1: TestimonialInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestimonial(arg0, to_candid_TestimonialInput_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestimonial(arg0, to_candid_TestimonialInput_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FileMetadata_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileMetadata): Promise<FileMetadata> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Testimonial_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Testimonial): Testimonial {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Project]): Project | null {
    return value.length === 0 ? null : from_candid_Project_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FileId;
    fileType: string;
    filename: string;
    projectId: _ProjectId;
    uploadedAt: _Timestamp;
    fileKey: _ExternalBlob;
}): Promise<{
    id: FileId;
    fileType: string;
    filename: string;
    projectId: ProjectId;
    uploadedAt: Timestamp;
    fileKey: ExternalBlob;
}> {
    return {
        id: value.id,
        fileType: value.fileType,
        filename: value.filename,
        projectId: value.projectId,
        uploadedAt: value.uploadedAt,
        fileKey: await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value.fileKey)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    insights: string;
    title: string;
    featured: boolean;
    createdAt: _Timestamp;
    tags: Array<string>;
    description: string;
    githubUrl: [] | [string];
    results: string;
    liveDemoUrl: [] | [string];
    datasetDescription: string;
    viewCount: bigint;
    approach: string;
    problemStatement: string;
}): {
    id: ProjectId;
    insights: string;
    title: string;
    featured: boolean;
    createdAt: Timestamp;
    tags: Array<string>;
    description: string;
    githubUrl?: string;
    results: string;
    liveDemoUrl?: string;
    datasetDescription: string;
    viewCount: bigint;
    approach: string;
    problemStatement: string;
} {
    return {
        id: value.id,
        insights: value.insights,
        title: value.title,
        featured: value.featured,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        githubUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.githubUrl)),
        results: value.results,
        liveDemoUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.liveDemoUrl)),
        datasetDescription: value.datasetDescription,
        viewCount: value.viewCount,
        approach: value.approach,
        problemStatement: value.problemStatement
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TestimonialId;
    name: string;
    role: string;
    quote: string;
    company: string;
    imageUrl: [] | [string];
    approved: boolean;
}): {
    id: TestimonialId;
    name: string;
    role: string;
    quote: string;
    company: string;
    imageUrl?: string;
    approved: boolean;
} {
    return {
        id: value.id,
        name: value.name,
        role: value.role,
        quote: value.quote,
        company: value.company,
        imageUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.imageUrl)),
        approved: value.approved
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileMetadata>): Promise<Array<FileMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FileMetadata_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Testimonial>): Array<Testimonial> {
    return value.map((x)=>from_candid_Testimonial_n21(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_FileMetadataInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileMetadataInput): Promise<_FileMetadataInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectInput): _ProjectInput {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_TestimonialInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestimonialInput): _TestimonialInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    insights: string;
    title: string;
    featured: boolean;
    tags: Array<string>;
    description: string;
    githubUrl?: string;
    results: string;
    liveDemoUrl?: string;
    datasetDescription: string;
    approach: string;
    problemStatement: string;
}): {
    insights: string;
    title: string;
    featured: boolean;
    tags: Array<string>;
    description: string;
    githubUrl: [] | [string];
    results: string;
    liveDemoUrl: [] | [string];
    datasetDescription: string;
    approach: string;
    problemStatement: string;
} {
    return {
        insights: value.insights,
        title: value.title,
        featured: value.featured,
        tags: value.tags,
        description: value.description,
        githubUrl: value.githubUrl ? candid_some(value.githubUrl) : candid_none(),
        results: value.results,
        liveDemoUrl: value.liveDemoUrl ? candid_some(value.liveDemoUrl) : candid_none(),
        datasetDescription: value.datasetDescription,
        approach: value.approach,
        problemStatement: value.problemStatement
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: string;
    quote: string;
    company: string;
    imageUrl?: string;
    approved: boolean;
}): {
    name: string;
    role: string;
    quote: string;
    company: string;
    imageUrl: [] | [string];
    approved: boolean;
} {
    return {
        name: value.name,
        role: value.role,
        quote: value.quote,
        company: value.company,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        approved: value.approved
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fileType: string;
    filename: string;
    projectId: ProjectId;
    fileKey: ExternalBlob;
}): Promise<{
    fileType: string;
    filename: string;
    projectId: _ProjectId;
    fileKey: _ExternalBlob;
}> {
    return {
        fileType: value.fileType,
        filename: value.filename,
        projectId: value.projectId,
        fileKey: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.fileKey)
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
